apiVersion: v2
name: cd4pe
description: An experimental helm chart for Puppet CD4PE
home: https://github.com/jarretlavallee/helm-charts
maintainers:
  - name: jarretlavallee
    email: jarret.lavallee@gmail.com

type: application
version: 0.1.1
appVersion: 3.8.0

dependencies:
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
