{{ if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cd4pe.fullname" . }}-object-store
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{ if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end }}
{{ end }}