apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cd4pe.fullname" . }}-secret
  labels:
    app: {{ include "cd4pe.name" . | quote }}
    chart: {{ include "cd4pe.chart" . | quote }}
    release: "{{ .Release.Name }}-secret"
    heritage: {{ .Release.Service | quote }}
  annotations:
{{- toYaml .Values.secret.annotations | nindent 4 }}
type: Opaque
data:
  {{- if .Values.uniqueId }}
  uniqueId: {{ .Values.uniqueId | b64enc | quote }}
  {{ else }}
  uniqueId: {{ randAlphaNum 16 | b64enc | b64enc | quote }}
  {{- end }}